#!/bin/bash
# Usage: calendar-nav <prev|next> <month> <year>
DIR="$1"
MONTH="$2"
YEAR="$3"

if [ "$DIR" = "prev" ]; then
    MONTH=$((MONTH - 1))
    if [ "$MONTH" -lt 1 ]; then
        MONTH=12
        YEAR=$((YEAR - 1))
    fi
else
    MONTH=$((MONTH + 1))
    if [ "$MONTH" -gt 12 ]; then
        MONTH=1
        YEAR=$((YEAR + 1))
    fi
fi

~/.config/eww/scripts/calendar "$MONTH" "$YEAR"
