#!/bin/bash
# Lists cached apps and updates eww variables (app0..app7)
CACHE="$HOME/.cache/eww/apps.cache"
[ -f "$CACHE" ] || ~/.files/configs/all/eww/widgets/launcher/scripts/cache-apps

APPS=$(head -8 "$CACHE")

EWW_ARGS=()
IDX=0
while IFS=$'\t' read -r exec_line name icon_path; do
    [ -z "$exec_line" ] && continue
    if [ -n "$icon_path" ] && [ -f "$icon_path" ]; then
        icon_markup="<img src=\"file://${icon_path}\" width=\"32\" height=\"32\"/>"
    else
        initial=$(echo "$name" | cut -c1 | tr '[:lower:]' '[:upper:]')
        icon_markup="<span size=\"x-large\" weight=\"bold\">${initial}</span>"
    fi
    EWW_ARGS+=("app${IDX}_exec=$exec_line")
    EWW_ARGS+=("app${IDX}_name=$name")
    EWW_ARGS+=("app${IDX}_icon=$icon_markup")
    EWW_ARGS+=("app${IDX}_visible=true")
    IDX=$((IDX + 1))
    [ $IDX -ge 8 ] && break
done <<< "$APPS"

for i in $(seq $IDX 7); do
    EWW_ARGS+=("app${i}_visible=false")
done

eww update "${EWW_ARGS[@]}"
