#!/bin/bash
# Usage: filter-apps [query]
# Filters cached apps by name words and updates eww variables (app0..app7)
QUERY="${1:-}"
CACHE="$HOME/.cache/eww/apps.cache"
[ -f "$CACHE" ] || ~/.config/eww/scripts/cache-apps

eww update search_query="$QUERY"

if [ -z "$QUERY" ]; then
    APPS=$(head -8 "$CACHE")
else
    APPS=$(awk -F'\t' -v q="$QUERY" '
    BEGIN { n = split(q, words, " ") }
    {
        name = $2
        ok = 1
        for (i = 1; i <= n; i++) {
            if (tolower(name) !~ tolower(words[i])) { ok = 0; break }
        }
        if (ok) print
    }' "$CACHE" | head -8)
fi

EWW_ARGS=()
IDX=0
while IFS=$'\t' read -r exec_line name icon_path; do
    [ -z "$exec_line" ] && continue
    if [ -n "$icon_path" ] && [ -f "$icon_path" ]; then
        icon_markup="<img src=\"file://${icon_path}\" width=\"32\" height=\"32\"/>"
    else
        initial=$(echo "$name" | cut -c1 | tr '[:lower:]' '[:upper:]')
        icon_markup="<span size=\"x-large\" weight=\"bold\">${initial}</span>"
    fi
    EWW_ARGS+=("app${IDX}_exec=$exec_line")
    EWW_ARGS+=("app${IDX}_name=$name")
    EWW_ARGS+=("app${IDX}_icon=$icon_markup")
    EWW_ARGS+=("app${IDX}_visible=true")
    IDX=$((IDX + 1))
    [ $IDX -ge 8 ] && break
done <<< "$APPS"

for i in $(seq $IDX 7); do
    EWW_ARGS+=("app${i}_visible=false")
done

eww update "${EWW_ARGS[@]}"
